// Mocks generated by Mockito 5.4.6 from annotations
// in runny_app/test/p0_p1_service_contracts_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:runny_app/models/subscription_models.dart' as _i6;
import 'package:runny_app/services/edge_function_result.dart' as _i2;
import 'package:runny_app/services/entitlement_service.dart' as _i3;
import 'package:runny_app/services/subscription_service.dart' as _i5;
import 'package:runny_app/services/training_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEdgeFunctionResult_0 extends _i1.SmartFake
    implements _i2.EdgeFunctionResult {
  _FakeEdgeFunctionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EntitlementDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementDataSource extends _i1.Mock
    implements _i3.EntitlementDataSource {
  @override
  _i4.Future<Object?> getEntitlementStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getEntitlementStatus, []),
            returnValue: _i4.Future<Object?>.value(),
            returnValueForMissingStub: _i4.Future<Object?>.value(),
          )
          as _i4.Future<Object?>);
}

/// A class which mocks [SubscriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionService extends _i1.Mock
    implements _i5.SubscriptionService {
  @override
  _i4.Future<List<_i6.SubscriptionPlan>> getPlans() =>
      (super.noSuchMethod(
            Invocation.method(#getPlans, []),
            returnValue: _i4.Future<List<_i6.SubscriptionPlan>>.value(
              <_i6.SubscriptionPlan>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i6.SubscriptionPlan>>.value(
                  <_i6.SubscriptionPlan>[],
                ),
          )
          as _i4.Future<List<_i6.SubscriptionPlan>>);

  @override
  _i4.Future<_i6.UserSubscription?> getActiveSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSubscription, []),
            returnValue: _i4.Future<_i6.UserSubscription?>.value(),
            returnValueForMissingStub:
                _i4.Future<_i6.UserSubscription?>.value(),
          )
          as _i4.Future<_i6.UserSubscription?>);

  @override
  _i4.Future<String> createPaymentLink(_i6.SubscriptionPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#createPaymentLink, [plan]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createPaymentLink, [plan]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createPaymentLink, [plan]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> cancelSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SubscriptionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionDataSource extends _i1.Mock
    implements _i5.SubscriptionDataSource {
  @override
  _i4.Future<List<Map<String, dynamic>>> fetchPlans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlans, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchActiveSubscription(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchActiveSubscription, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<_i2.EdgeFunctionResult> createPayment(
    String? planId,
    String? idempotencyKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPayment, [planId, idempotencyKey]),
            returnValue: _i4.Future<_i2.EdgeFunctionResult>.value(
              _FakeEdgeFunctionResult_0(
                this,
                Invocation.method(#createPayment, [planId, idempotencyKey]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.EdgeFunctionResult>.value(
              _FakeEdgeFunctionResult_0(
                this,
                Invocation.method(#createPayment, [planId, idempotencyKey]),
              ),
            ),
          )
          as _i4.Future<_i2.EdgeFunctionResult>);

  @override
  _i4.Future<void> requestCancellation() =>
      (super.noSuchMethod(
            Invocation.method(#requestCancellation, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TrainingPlanJobClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrainingPlanJobClient extends _i1.Mock
    implements _i8.TrainingPlanJobClient {
  @override
  _i4.Future<_i2.EdgeFunctionResult> enqueue(Map<String, Object?>? body) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [body]),
            returnValue: _i4.Future<_i2.EdgeFunctionResult>.value(
              _FakeEdgeFunctionResult_0(
                this,
                Invocation.method(#enqueue, [body]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.EdgeFunctionResult>.value(
              _FakeEdgeFunctionResult_0(
                this,
                Invocation.method(#enqueue, [body]),
              ),
            ),
          )
          as _i4.Future<_i2.EdgeFunctionResult>);
}
